Update README.md
WATonomous/wato_finance_system pull request #75
Opened 2023-01-13 01:09 UTC by NicholasLin718

Instructions for firebase-admin in the backend used in this [ticket.](https://github.com/WATonomous/wato_finance_system/issues/61)

2023-01-15 22:50 UTC, ansonjwhe requested changes

2023-01-15 22:50 UTC, ansonjwhe commented on .gitignore
> +/backend/serviceAccountKey.json
create a #firebase section for this

2023-01-15 22:50 UTC, ansonjwhe commented on README.md
> +To be able to use `firebase-admin`, select the gear icon next to the Project Overview screen, go to **Project Settings** > **Service Accounts** and generate a new private key. Name the file `serviceA
use a numbered list like the other instructions to break down the steps. remove the last step, the gitignore will be updated for all devs once this PR is merged

2023-01-18 05:13 UTC, victorzheng02 approved these changes

2023-01-19 02:30 UTC, ansonjwhe approved these changes

2023-01-19 03:28 UTC, merged